CREATE OR REPLACE TRIGGER trigger_restricted
BEFORE INSERT OR UPDATE OR DELETE ON patient
REFERENCING OLD AS o NEW AS n
FOR EACH ROW

DECLARE 

BEGIN 
	IF(TO_CHAR(SYSDATE, 'HH24:MI') NOT BETWEEN '04:00' AND '06:00')
	THEN
	RAISE_APPLICATION_ERROR(-20124,'YOU CAN MANIPULATE Patient TABLE ONLY BETWEEN 4:00 AM and 6:00 AM. PLEASE TRY IN BETWEEN THAT TIME!!!');
	END IF;
END;
/